# Peer Review
Based on [Project 1 rubric](https://github.com/txt/se22/blob/main/docs/proj1.md#rubric)
Template By Neeloy Gomes (https://github.com/ntgomes)
Grading (https://github.com/sam16222/CSC510_43)
Graded by Tyler Craine

| **Criteria**                                                                       | **Points** | **Evidence**                                                                                                                                      |
|------------------------------------------------------------------------------------|------------|---------------------------------------------------------------------------------------------------------------------------------------------------|
| Video 1                                                                            | 0          | There is no video                                                                                                                                 |
| Video 2                                                                            | 0          | There is no video                                                                                                                                 |
| Workload is spread over the whole team                                             | 2          | https://github.com/sam16222/CSC510_43/graphs/contributors                                                                                             |
| Number of commits                                                                  | 3          | https://github.com/sam16222/CSC510_43/commits/main                                                                                    |
| Number of commits by different people                                              | 2          | https://github.com/sam16222/CSC510_43/graphs/contributors                                                                                   |
| Issue reports                                                                      | 1          | https://github.com/sam16222/CSC510_43/issues                                                                                                |
| Number of issues closed                                                            | 2          | https://github.com/sam16222/CSC510_43/issues?q=is%3Aissue+is%3Aclosed                                                                                      |
| DOI badge                                                                          | 3          | https://github.com/sam16222/CSC510_43<br>https://zenodo.org/record/7109114                                                                      |
| Docs auto-generated and neat                                                       | 1          | Not auto-generated, but something is there:<br>https://github.com/sam16222/CSC510_43/tree/main/docs                                            |
| Docs show point descriptions of each class<br>and function                         | 0          | There are no docs that show this if you don't count <br>code comments                                                                             |
| Docs show common use cases and mini<br>tutorials                                   | 1          | https://github.com/sam16222/CSC510_43/blob/main/README.md                                                                                 |
| Docs tell a story about the why                                                    | 3          | https://github.com/sam16222/CSC510_43/blob/main/README.md                                                                                  |
| Docs has a short animated video                                                    | 0          | There is no such video                                                                                                                            |
| Use of version control tools                                                       | 3          | https://github.com/sam16222/CSC510_43                                                                                                           |
| Use of style checking tools                                                        | 2          | None that I can see, but the IDE used could be providing this service                                                                              |
| Use of code formatters                                                             | 2          |https://github.com/sam16222/CSC510_43                                                                                |
| Use of syntax checkers                                                             | 2          | https://github.com/sam16222/CSC510_43                                                                                       |
| Use of code coverage                                                               | 3          | https://github.com/sam16222/CSC510_43/blob/main/.github/workflows/workflow.yml                 |
| Other automated analysis tools                                                     | 3          | https://github.com/sam16222/CSC510_43/blob/main/.github/workflows/python-app.yml                                                                               |
| Test cases exist                                                                   | 3          | https://github.com/sam16222/CSC510_43/tree/main/tests                                       |
| Test cases are routinely executed                                                  | 3          | https://github.com/sam16222/CSC510_43/blob/main/.github/workflows/python-app.yml                                                            |
| CONTRIBUTING.md is meaningful                                                      | 3          | https://github.com/sam16222/CSC510_43/blob/main/CONTRIBUTING.md                                                                                |
| Issues are discussed before they are closed                                        | 0          | https://github.com/sam16222/CSC510_43/issues?q=is%3Aissue+is%3Aclosed                                                                                                |
| Existence of chat channel                                                          | 3          | One's not mentioned but the team are on the README.md and there's emails associated with the GitHub page                                                                                                                   |
| A large proportion of issues are for fixing<br>failing test cases                  | 1          | https://github.com/sam16222/CSC510_43/issues?q=is%3Aissue+is%3Aclosed                                                                                               |
| Evidence that the whole team is using the<br>same tools                            | 1          | https://github.com/sam16222/CSC510_43/blob/main/.DS_Store|only file found relating to tool in the repo
| Evidence that members of the team are<br>committing to multiple places in the code | 3          | Evident from commit history descriptions https://github.com/sam16222/CSC510_43/commits/main                                  |
| Short release cycles                                                               | 3          | Evident by the weekly deadlines                                                                                                                   |
| _Total_                                                                            | **53**     | This is mostly a good repo. Maybe could've taken advantage of GitHub's features more (max 84 points)                                                                          |
